<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

  <!-- Exclude Unity Scripts from Console App build -->
  <ItemGroup>
    <Compile Remove="DrawingGrid.cs" />
    <Compile Remove="NeuralNetworkInference.cs" />
  </ItemGroup>

</Project>
